Mission04_chasejr/Models/Validator.cs
using System;
using System.Collections.Generic;
/*this line will allow me to use the range validator class*/
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_chasejr.Models
{
    public class Validator
    {
        /* For each field of the form make a validator that will make sure the number entered is 
           between 0 and 100. I used a byte type because the number doesn't need to be larger than 100. */
        [Range(0,100,ErrorMessage = "Enter a number between 0 and 100 in every field")]
        public byte Assignments { get; set; }
        [Range(0,100,ErrorMessage="Enter a number between 0 and 100 in every field")]
        public byte Group_project { get; set; }
        [Range(0,100,ErrorMessage="Enter a number between 0 and 100 in every field")]
        public byte Quizzes { get; set; }
        [Range(0,100,ErrorMessage="Enter a number between 0 and 100 in every field")]
        public byte Midterm { get; set; }
        [Range(0,100,ErrorMessage="Enter a number between 0 and 100 in every field")]
        public byte Final { get; set; }
        [Range(0,100,ErrorMessage="Enter a number between 0 and 100 in every field")]
        public byte Intex { get; set; }
    }
}

Mission04_chasejr/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
/* Make sure to import the Models directory so you can call the validator class */
using Mission04_chasejr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_chasejr.Controllers
{
    public class HomePageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }

        /* This will catch the post method that is called and return an instance of the validator 
         * class in the model object */
        [HttpPost]
        public IActionResult Calculator(Validator model)
        {
            return View();
        }
    }
}

Mission04_chasejr/Views/HomePage/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Validator;
<!--Grade Calculator Based on IS413 Syllabus
   Assignments 50 %
   Group Project 10 %
   Quizzes 10 %
   Midterm Exam 10 %
   Final Exam 10 %
   INTEX 10 %
   -->
<div class="form content">
    <h1>Grade Calculator:</h1>
    Input the percentage you score in each grade category to see what your overall class grade would be!
    <!--Create a form for the user to input their percentage scores in each grade category
        and make a submit button call the post method-->
    <form method="post">
        <br />
        <label>Assignments</label>
        @* use the asp-for tag helper in place of the name of each html input tag so that their values will
           be passed when the form is submitted *@
        <input type="number" asp-for="Assignments" id="assignments"><br /><br />
        <label>Group Project</label>
        <input type="number" asp-for="Group_project" id="group_project"><br /><br />
        <label>Quizzes</label>
        <input type="number" asp-for="Quizzes" id="quizzes"><br /><br />
        <label>Midterm Exam</label>
        <input type="number" asp-for="Midterm" id="midterm"><br /><br />
        <label>Final Exam</label>
        <input type="number" asp-for="Final" id="final"><br /><br />
        <label>Intex</label>
        <input type="number" asp-for="Intex" id="intex"><br /><br />
        <!--Give them a way to initiate the validation-->
        <input id="grade" type="submit" value="Calculate Grade" />
        <br />
    </form>
</div>

<div asp-validation-summary="All"></div>
<div class="content">
    <!--Provide a space for the message to be printed-->
    <p id="message" class="message"></p>
</div>
<!--Import your javascript sources being used-->

Mission04_chasejr/Views/HomePage/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade_Calculator_Page";
}
<!--Chase's Index Grade calculator page for IS413-->


    <div class="content">
        <h1>Hi, my name is Chase!</h1>
    </div>
    <!--Picture of me doing something I love-->
    <div class="content">
        <img src="img/climbing_photo.jpeg" />
    </div>
    <!--Paragraph of what I want to get out of this class-->
    <div class="content">
        <h1>Hopes for IS413:</h1>
        <p>
            Over the course of this class, I hope to learn marketable skills that I can include on my resume.<br />
            I want to get a better grasp of what working on large-scale projects in teams will be like in the industry.<br />
            I want to find out if development is one of my interests that I'd like to pursue for my actual career.<br />
            I also want to make meaningful connections with my classmates, have fun along the way, and get an A in the class :)
        </p>
    </div>
    <!--Make a list of my top 3 jobs below-->
    <div class="content">
        <h1>Jobs I'd Be Interested In:</h1>
        <ol>
            <li>Database Manager</li>
            <li>Data Analyst (something sports related could be cool)</li>
            <li>Tech Consulting</li>
        </ol>
    </div>
   

Mission04_chasejr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <!--This will generate a fav-Icon-->
    <link rel="icon" type="image/x-icon" href="~/img/climbing_photo.jpeg">
    <!--Import your style sheets that are being used-->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/grader_styling.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="HomePage" asp-action="Index">Home</a>
        <a asp-controller="HomePage" asp-action="Calculator">Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>
    @*Each page will call the javascript functions on loading, the GradeCalculator.js page is currently
      not meaningful because the controller and model are now handling validating. It is printing an alert 
      statement currently though*@
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/js/GradeCalculator.js"></script>
</body>
</html>